/* 법령 데이터 — 면제 사유(EXEMPT_META) 및 사전절차 체크리스트(CHECKS_META) */
export const EXEMPT_META = {
  disaster:{label:'재해복구 등 원상복구를 목적으로 하는 사업',law:'지방재정법 제37조 제3항 제1호'},
  heritage:{label:'문화재수리 사업',law:'지방재정법 제37조 제3항 제2호 (문화재수리 등에 관한 법률 제2조 제1호)'},
  pubcorp:{label:'지방공사·공단 설립 사업',law:'지방재정법 제37조 제3항 제3호 (지방공기업법 제49조·제76조)'},
  health_fire:{label:'보건소·소방기관 건축 사업 (복합시설은 심사 대상)',law:'지방재정법 제37조 제3항 제4호'},
  decree:{label:'시행령 별표 당연면제 사업 (재해예방·하수도정비기본계획 반영사업 등)',law:'지방재정법 시행령 별표 제1호~제24호'}
};
export const CHECKS_META = {
  'midterm': {title:'중기지방재정계획 반영 확인', level:'critical', badge:'must',
    desc:'파주시 중기지방재정계획(5개년)에 해당 사업이 반영되어 있어야 합니다.',
    law:'지방재정법 제33조 제11항 / 심사규칙 제4조', dept:'담당부서: 기획예산과'},
  'plan': {title:'사업기본계획 수립 완료', level:'critical', badge:'must',
    desc:'기본설계 용역 착수 전에 투자심사를 의뢰해야 합니다.',
    law:'심사규칙 제4조 제1항', dept:'담당부서: 사업부서'},
  'priority': {title:'투자사업 우선순위표 작성', level:'critical', badge:'must',
    desc:'제출 서류에 반드시 포함되어야 합니다.',
    law:'심사규칙 제4조 제3항 제2호', dept:'담당부서: 기획예산과'},
  'budget': {title:'회계별 가용재원 판단서 작성', level:'critical', badge:'must',
    desc:'예산부서에서 작성·확인합니다. 최근 3년 결산 기준.',
    law:'심사규칙 제4조 제3항 제3호', dept:'협조부서: 기획예산과 예산팀'},
  'national': {title:'국비 확보 여부 확인', level:'important', badge:'caution',
    desc:'원칙적으로 국비 확보 후 투자심사를 의뢰해야 합니다. (공모선정사업 등 예외 있음)',
    law:'심사규칙 제4조 관련', dept:'담당부서: 사업부서'},
  'gyeonggi': {title:'경기도비 지원 검토의견서 징구', level:'important', badge:'caution',
    desc:'도비 보조사업의 경우 경기도 재정정책과로부터 검토의견서를 받아야 합니다.',
    law:'별지 제3호 서식', dept:'협조기관: 경기도 재정정책과'},
  'tangibility': {title:'타당성조사 이행 필수 (500억 이상)', level:'critical', badge:'must',
    desc:'총사업비 500억원 이상으로 타당성조사 대상입니다. 한국지방행정연구원 또는 한국지방재정공제회에 의뢰.',
    law:'지방재정법 제37조의2 제1항', dept:'협조기관: 한국지방행정연구원'},
  'no_tangibility': {title:'타당성조사 (500억 이상 해당)', level:'na', badge:'skip',
    desc:'총사업비 500억원 미만으로 타당성조사 의무 대상이 아닙니다.',
    law:'지방재정법 제37조의2', dept:''},
  'remodel': {title:'청사 리모델링 가능 여부 검토서', level:'important', badge:'caution',
    desc:'본청 및 의회청사 신축사업의 경우 리모델링 검토서를 첨부해야 합니다.',
    law:'심사규칙 제4조 제3항 제4호', dept:'담당부서: 건축담당'},
  'resim_comply': {title:'이전 심사 조건부 사항 이행내용 보완', level:'critical', badge:'must',
    desc:'종전 투자심사 결과 재검토·조건부 통보 사항에 대한 이행내용을 의뢰서에 구체적으로 기재해야 합니다.',
    law:'심사규칙 제5조 제2항 제2호', dept:'담당부서: 사업부서'},
};
